"""empty message

Revision ID: 161093c18654
Revises: 
Create Date: 2019-02-20 00:27:02.991907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161093c18654'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_authors', sa.Column('addr', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_authors', 'addr')
    # ### end Alembic commands ###
